version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: 'redis:6.2.8'

  wkhtmltopdf:
    image: 'openlabs/docker-wkhtmltopdf-aas:latest'
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: ./prod.dockerfile
    command: sh -c "python manage.py migrate && gunicorn -w 4 check_maker.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env.prod
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - media:/home/app/web/media/
    depends_on:
      - db
      - redis
      - wkhtmltopdf

  celery:
    build:
      context: .
      dockerfile: ./prod.dockerfile
    command: celery --app check_maker worker --loglevel info
    env_file:
      - ./.env.prod
    restart: on-failure
    volumes:
      - media:/home/app/web/media/
    depends_on:
      - app

  flower:
    image: 'mher/flower:1.2'
    env_file:
      - ./.env.prod
    ports:
      - "5555:5555"
    restart: on-failure
    depends_on:
      - celery

volumes:
  postgres_data:
  media:
