version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: 'redis:6.2.8'

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: sh -c "python manage.py migrate && python manage.py loaddata check_maker/api/fixtures/data.json && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app/
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: celery --app check_maker worker --loglevel info
    env_file:
      - ./.env.dev
    restart: on-failure
    depends_on:
      - app

volumes:
  postgres_data:
