version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
